export const UNIFORM_BUFFER_ALIGNMENT = 256;
export const RENDER_UNIFORM_BUFFER_SIZE = Math.ceil(
    (80 * Float32Array.BYTES_PER_ELEMENT) / UNIFORM_BUFFER_ALIGNMENT
) * UNIFORM_BUFFER_ALIGNMENT;
export const COMPUTE_UNIFORM_BUFFER_SIZE = 176;
