// wasm/brain_tensor_params.h
// [Tensor Physics] GENERATED by scripts/gen_wasm_params.mjs from
// COMPUTE_UNIFORM_LAYOUT in src/shaders/uniform-layout.js — do not hand-edit.
//
// This is the C ABI mirror of the WGSL `TensorParams` uniform struct. The JS
// bridge (src/wasm-engine.js) fills it through COMPUTE_UNIFORM_OFFSETS, the
// WebGPU path fills the same offsets in its uniform buffer, and the C++ engine
// reads it here — one declaration, three consumers.
//
// Regenerate with:  node scripts/gen_wasm_params.mjs
// Verified by:      npm test  (tests/test_uniform_layout.js)

#pragma once

#include <cstdint>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct BrainTensorParams {
    float time; // byte offset 0
    uint32_t voxelDim; // byte offset 4
    float frequency; // byte offset 8
    float amplitude; // byte offset 12
    float spikeThreshold; // byte offset 16
    float smoothing; // byte offset 20
    float style; // byte offset 24
    float _pad0[1]; // WGSL alignment filler
    float stimulusPos[3]; // V2.2 Stimulus Fields — byte offset 32
    float stimulusActive; // byte offset 44
    float hypoxiaStress; // byte offset 48
    float metabolicRate; // byte offset 52
    float mitochondrialFunction; // byte offset 56
    float fluidActive; // byte offset 60
    float electricalActive; // byte offset 64
    float mercuryActive; // byte offset 68
    float cognitiveLoad; // byte offset 72
    float stress; // byte offset 76
    float heavyMetal; // byte offset 80
    float pad2; // byte offset 84
    float aiInfluence; // [SynaptiX] AI Tensor Mirror params — byte offset 88
    float resonanceThreshold; // byte offset 92
    float synaptiXActive; // byte offset 96
    float fiberCoupling; // [V3.2] Fiber-volume coupling — byte offset 100
    float cognitiveDissonance; // byte offset 104
    float pad3; // byte offset 108
    float decayRate; // [Phase 21] Neuromodulator physics — byte offset 112
    float diffusionRate; // byte offset 116
    float pulseSaturation; // byte offset 120
    float trailLength; // byte offset 124
    float retentionBias[4]; // x=frontal, y=occipital, z=temporal, w=parietal — byte offset 128
    float lesionCenter[3]; // byte offset 144
    float lesionActive; // byte offset 156
    float lesionRadius; // byte offset 160
    float decimation; // byte offset 164
    float stimulusRadius; // [Paint Energy] brush radius (0 = legacy fixed sigma 0.5) — byte offset 168
    float stimulusErase; // [Paint Energy] erase/damping mode flag (>0.5 = erase) — byte offset 172
} BrainTensorParams;

// Number of floats in the struct (= sizeof(BrainTensorParams) / 4).
#define BTE_PARAMS_FLOAT_COUNT 44u

// Byte size of the struct. bte_params_byte_size() returns this at runtime so
// the JS bridge can refuse to run against a stale .wasm.
#define BTE_PARAMS_BYTE_SIZE 176u

#ifdef __cplusplus
} // extern "C"
#endif
