#!/usr/bin/env node
// scripts/gen_tensor_fixture.mjs
// [Tensor Physics] Regenerates the cross-implementation golden fixture by
// running the JavaScript reference stepper over tests/golden-scenario.js.
//
//   node scripts/gen_tensor_fixture.mjs
//
// Outputs:
//   tests/fixtures/tensor-field-golden.bin   32³ float32, little-endian
//   tests/fixtures/tensor-field-golden.json  scenario + summary statistics
//
// tests/test_tensor_physics.js re-runs the stepper and requires a bit-exact
// match; wasm/tests/golden_step_test.cpp runs the C++ engine over the same
// scenario and requires a match within GOLDEN_EPSILON. Regenerate only when the
// physics spec deliberately changes — a diff here is a visual change.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';

import { GOLDEN_SCENARIO, GOLDEN_EPSILON, runGoldenScenario, summarizeField } from '../tests/golden-scenario.js';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const field = runGoldenScenario();
const bytes = Buffer.from(field.buffer, field.byteOffset, field.byteLength);
const sha256 = createHash('sha256').update(bytes).digest('hex');

writeFileSync(join(repoRoot, 'tests', 'fixtures', 'tensor-field-golden.bin'), bytes);
writeFileSync(
    join(repoRoot, 'tests', 'fixtures', 'tensor-field-golden.json'),
    JSON.stringify({
        _comment: 'GENERATED by scripts/gen_tensor_fixture.mjs from the JS reference stepper. See docs/tensor-physics.md §9.',
        scenario: GOLDEN_SCENARIO,
        epsilon: GOLDEN_EPSILON,
        voxelCount: field.length,
        sha256,
        stats: summarizeField(field),
    }, null, 2) + '\n'
);

console.log(`[gen_tensor_fixture] ${field.length} voxels, sha256 ${sha256.slice(0, 16)}…`);
console.log('[gen_tensor_fixture]', JSON.stringify(summarizeField(field)));
